# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ad809b27397030bb35dbcef8a5e2ae41811be55a07ec030535a8df201d0a2f782c4ba57fe78573c495344623fe49e104930bf6f7ee3a054e985a6392e68adb1

test:
  secret_key_base: 14d5dfce1c889e4727f9994f4e58f9215a8f909b38bcdb867ff04da25743b27684d157d2f942a12e826f464e4a54eddc0cd489016e86c816106a90d0dd28e114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
